name: Start EC2 Instance

on:
  workflow_dispatch:  # Manual trigger
  # You can also add other triggers like:
  schedule:
    - cron: '30 7 * * *'  # Daily at 6 AM UTC
  # push:
  #   branches: [ main ]

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run main tasks
        run: |
          echo "Running your main tasks here..."
          # Your actual job steps go here

  start-ec2:
    needs: main-job  # This ensures stop runs after main job completes
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: start EC2 Instance
        run: |
          aws ec2 describe-instances --instance-ids i-0d306b2857341dcf2 --query 'Reservations[0].Instances[0].State.Name' --output text
          aws ec2 start-instances --instance-ids i-0d306b2857341dcf2
          aws ec2 wait instance-running --instance-ids i-0d306b2857341dcf2
          echo "EC2 instance started successfully"
